author: Julien Bordet
description: Blog personnel
highlighter: pygments
permalink: /blog/:categories/:year/:month/:day/:title.html
markdown: kramdown
exclude: ["Rmd", ".DS_Store", "README.md"]
excerpt_separator: <!--more-->
